### PR TITLE
Widen GUI.visualizer field.

### PR DESCRIPTION
**Pull request by tkoolen**
Allow types other than `MechanismVisualizer` for the `visualizer` field of `GUI`, as long as they adhere to a now-documented simple interface. Basically provides a hook for a user to add their own custom visualization elements, handy for e.g. visualization of contact forces, intermediate controller results, etc.

@rdeits, is this how you would do it? I suppose you could also write your own `MyVisualizer <: MeshCat.AbstractVisualizer` since `MechanismVisualizer` is parameterized on the type of its `visualizer` field, and then you could overload `copyto!(vis::MechanismVisualizer{<:Any, MyVisualizer}, state)` for that visualizer. Is that better?

### CODE REVIEW

**Comment by rdeits** [comment]
I think this looks good, but I think it would make more sense for the user to implement `WebIO.render()` rather than `MeshCatMechanisms.visualizer()`. It doesn't actually matter if the viewer produces a MeshCat.Visualizer, only that it produces something that can be rendered. 

We might need to implement `WebIO.render(mvis::MechanismVisualizer) = WebIO.iframe(mvis.visualizer.core)` to make this work, but I think that's probably the right thing to do anyway.

**Comment by tkoolen** [comment]
Hmm, yeah I kind of like that. I see that MeshCat [defines](https://github.com/rdeits/MeshCat.jl/blob/6b062945f92227ea59054c077c0f2a64e8457856/src/visualizer.jl#L57)

```julia
WebIO.render(core::CoreVisualizer) = core.scope
```
though, so I do wonder if it makes sense that a `MechanismVisualizer`'s `WebIO.render` method does something different.

**Comment by tkoolen** [comment]
Going with this for now.

**Comment by rdeits** [comment]
Works for me. I'm still a bit in limbo while WebIO reinvents itself again.

**Pull request merged**
