### PR TITLE
remove all branch restrictions on travis

### PR DESCRIPTION
**Pull request by rdeits**
(this is just a hunch)

### CODE REVIEW

**Comment by rdeits** [comment]
@tkoolen ok, Travis is working on this PR. I'm going to try turning the `branches: only: master` back on without your version tag regex

**Comment by rdeits** [comment]
Yeah, that works too. Somehow that version tag regex is breaking Travis's PR builds.

**Comment by tkoolen** [comment]
Same regex is working fine for RigidBodyDynamics though (and it has for RigidBodySim). Strange.

**Comment by rdeits** [comment]
Another hypothesis: you have a slash in your branch name and...something something something?

**Pull request closed without merging**
