### PR TITLE
require new lcmcore

### PR DESCRIPTION
**Pull request by rdeits**

### CODE REVIEW

**Comment by tkoolen** [comment]
Travis isn't working again for some reason, both for RigidBodySim and HumanoidLCMSim...

**Comment by rdeits** [comment]
Hm, I just turned it off and on again and that didn't work.

**Comment by tkoolen** [comment]
Travis says "Job Rejected": https://travis-ci.org/JuliaRobotics/RigidBodySim.jl/requests.

**Comment by rdeits** [comment]
Oh, also, this is a PR into a branch, not into master. Perhaps that's the problem?

**Comment by tkoolen** [comment]
Ahhh, that's it. Man, should really put up a big blinking sign if the base branch is not master.

**Pull request merged**
